name: suika-windows-vs
on:
  push:
    types: [master,actions]
  pull_request:
    types: [synchronize,opened]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v1.0.2

      - run: |
          cd build/vs/suika
          msbuild /p:Configuration=Release
