name: suika-linux
on:
  push:
  pull_request:
jobs:
  linux:
    runs-on: "ubuntu-22.04"
    name: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt update
          sudo apt install -y libasound2-dev libx11-dev libxpm-dev 
          cd build/linux
          ./build-libs.sh
          make
