name: suika-windows-vs
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - run: |
          cd build/vs
          powershell -command "Expand-Archive libs.zip -DestinationPath ."
          cd suika
          msbuild /p:Configuration=Release
