name: suika-windows-vs
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - run: |
          cd build/vs
          call powershell -command "Expand-Archive libs.zip"
          cd suika
          msbuild /p:Configuration=Release
